apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopix
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api.yaml
  - front.yaml
  - commandes.yaml
  - ingress.yaml
labels:
  - pairs:
      fil-rouge: shopix
    includeSelectors: true
